############################################################
# Dockerfile to build Nginx Amplify Agent autotests
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM ubuntu:20.04

# File Author / Maintainer
MAINTAINER Andrei Belov

# create required groups/users
RUN groupadd -r mysql && useradd -r -g mysql mysql

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install tzdata

RUN apt-get install -y -q wget apt-transport-https \
    curl ca-certificates gnupg2 lsb-release

# download certificate and key from the customer portal (https://cs.nginx.com)
# and copy to the build context
ADD docker/test-plus/nginx-repo.crt /etc/ssl/nginx/
ADD docker/test-plus/nginx-repo.key /etc/ssl/nginx/

# get other files required for installation
RUN wget -q -O - http://nginx.org/keys/nginx_signing.key | apt-key add -
RUN wget -q -O /etc/apt/apt.conf.d/90nginx https://cs.nginx.com/static/files/90nginx

# install NGINX Plus
RUN printf "deb https://plus-pkgs.nginx.com/ubuntu `lsb_release -cs` nginx-plus\n" >/etc/apt/sources.list.d/nginx-plus.list \
 && apt-get update \
 && apt-get install -y nginx-plus \
 && cp /usr/sbin/nginx /usr/sbin/nginx2

# install NGINX OS and some other applications
RUN apt-get install -y --fix-missing \
     build-essential \
     curl \
     mysql-server-8.0 \
     nano \
     net-tools \
     php-fpm \
     python3 \
     python3-dev \
     python3-pytest \
     python3-pytest-xdist \
     python3-hamcrest \
     python3-mock \
     python3-freezegun \
     python3-requests \
     python3-requests-mock \
     python3-psutil \
     python3-distro \
     python3-gevent \
     python3-greenlet \
     python3-rstr \
     python3-ujson \
     python3-netifaces \
     python3-pymysql \
     tar \
     wget

# enforce mysqld default settings
RUN service mysql stop
RUN sed -i -e 's,^# pid-file,pid-file,' -e 's,^# socket,socket,' -e 's,^# port,port,' -e 's,^# datadir,datadir,' /etc/mysql/mysql.conf.d/mysqld.cnf

# configure for php-fpm
RUN rm -rf /run && mkdir -p /run/php/

# add fastcgi_params and php-fpm.conf for nginx
ADD docker/test-plus/fastcgi_params /etc/nginx/fastcgi_params
ADD docker/test-plus/php-fpm.conf /etc/nginx/conf.d/php-fpm.conf

# overwrite default www.conf for php-fpm and add second one
ADD docker/test-plus/php-fpm-www.conf /etc/php/7.4/fpm/pool.d/www.conf
ADD docker/test-plus/php-fpm-www2.conf /etc/php/7.4/fpm/pool.d/www2.conf

# add test .php file to /var/www/php-fpm root
ADD docker/test-plus/test.php /var/www/php-fpm/test.php

# install basic python tools
RUN curl https://bootstrap.pypa.io/get-pip.py | python3 - \
 && pip install supervisor

# install agent requirements:
ADD docker/test-plus/requirements.txt /etc/naas/requirements.txt
RUN pip install -I -r /etc/naas/requirements.txt

# install test requirements
RUN pip install \
    timeout-decorator

# set some environment variables
ENV AMPLIFY_ENVIRONMENT testing
ENV PYTHONPATH /amplify

# set the default directory where CMD will execute
WORKDIR /amplify

# add config files
ADD docker/test-plus/nginx.conf /etc/nginx/nginx.conf
ADD docker/test-plus/nginx2.conf /etc/nginx/nginx2.conf
ADD docker/test-plus/nginx_bad_status.conf /etc/nginx/nginx_bad_status.conf
ADD docker/test-plus/nginx_syslog.conf /etc/nginx/nginx_syslog.conf
ADD docker/test-plus/supervisord-ubuntu2004.conf /etc/supervisord.conf
ADD docker/test-plus/nginx_no_logs.conf /etc/nginx/nginx_no_logs.conf

# add ssl stuff
ADD docker/test-plus/amplify-agent-test.crt /etc/nginx/certs.d/amplify-agent-test.crt
ADD docker/test-plus/amplify-agent-test.key /etc/nginx/certs.d/amplify-agent-test.key

# set the home dir of the mysql user
RUN usermod -d /var/lib/mysql/ mysql

CMD bash
